<?php

namespace Candonga\Data\Entities;

use Faker\Provider\Uuid;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    public $table = 'customers';

    public $dates = ['created_at', 'updated_at', 'deleted_at', 'date_of_birth'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'date_of_birth',
        'status'
    ];

    public static function getFieldsWithNiceNames()
    {
        return [

        ];
    }

    public function products()
    {
        return $this->hasMany(Product::class);
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function($record){
            $record->uuid = Uuid::uuid();
        });
    }
}
